routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['verified' => true]);
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
Route::get('verifyemail/{token}','Auth\RegisterController@verify');
Route::group(['middleware' => ['auth','verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('artikel', 'ArtikelController');
    Route::post('/artikelFormData/{id}','ArtikelController@update');
    Route::post('deleteImageIsi','ArtikelController@deleteImageIsi');
    Route::get('getArtikel','ArtikelController@getTableArtikel');
    Route::put('gantiStatusArtikel/{id}','ArtikelController@gantiStatus');
    Route::resource('kategori', 'KategoriArtikelController');
    Route::get('getKategori','KategoriArtikelController@getTableKategori');
    Route::put('gantiStatusKategori/{id}','KategoriArtikelController@gantiStatus');
    Route::resource('menuGrouping', 'MenuGroupingController');
    Route::get('/getMenu','MenuGroupingController@getMenu');
    Route::get('usersIndex','ManagementUsersController@usersIndex');
    Route::get('createUsers','ManagementUsersController@createUsers');
    Route::post('oprationUsers','ManagementUsersController@storeUsers');
    Route::delete('oprationUsers/{id}','ManagementUsersController@destroyUsers');
    Route::get('oprationUsers/{id}/edit','ManagementUsersController@editUsers');
    Route::put('oprationUsers/{id}/','ManagementUsersController@updateUsers');    
    Route::get('getUsers','ManagementUsersController@getUsers');
    Route::get('roleAndPermission','ManagementUsersController@roleAndPermission');
    Route::post('addRole','ManagementUsersController@addRole');
    Route::post('addPermission','ManagementUsersController@addPermission');
    Route::resource('sectionArtikel', 'SectionArtikelController');
    Route::get('getSection','SectionArtikelController@getSection');
    Route::resource('kategoriPage', 'KategoriPageController');
    Route::get('getPagePerKategori/{id}','KategoriPageController@getPagePerKategori')->name('getPagePerKategori');
    Route::resource('page', 'PageController');
    // Route::get('getApi','ManagementUsersController@getApi');
});

resources/views/admin/page/create.blade.php
@extends('layouts.app')
@section('title')
    Tambah Page
@endsection
@section('headerPage')
    Tambah Page
@endsection
@section('quickAction')
    <ul class="m-nav">
        <li>
            <li class="m-nav__section m-nav__section--first">
                <span class="m-nav__section-text">Quick Actions</span>
            </li>
            <li class="m-nav__item">
                <a href="{{ route('page.index') }}" class="m-nav__link">
                    <i class="m-nav__link-icon flaticon-share"></i>
                    <span class="m-nav__link-text">Lihat Page</span>
                </a>
            </li>
        </li>
    </ul>
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif
<form method="POST" action="{{route('page.store')}}" enctype="multipart/form-data">
    @csrf
        <div class="form-group">
            <label>Judul</label>
            <input type="name" class="form-control" name="judul" placeholder="Masukan Judul Page">
        </div>
        <div class="form-group">
            <label>Kategori</label>
            <select name="kategori_id" id="kategori_id" class="form-control">
                <option value="">--------Pilih Kategori--------</option>
                @foreach ($kategoris as $kategori)
                <option value="{{$kategori->id}}">{{$kategori->nama}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="">Header Image</label>
            <input type="file" name="headerImage" class="form-control">
        </div>
        <div class="form-group">
            <label for="">Isi</label>
            <textarea name="isi" id="isi" cols="30" rows="10" class="form-control summernote" placeholder="Masukan Isi Page"></textarea>            
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection

resources/views/admin/page/index.blade.php
@extends('layouts.app')
@section('title')
    Lists All Page
@endsection
@section('headerPage')
    Lists All Page
@endsection
@section('isi')
<div class="m-portlet m-portlet--head-lg">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="la la-list"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Lists All Page
                </h3>
            </div>

        </div>
    </div>
    <div class="m-portlet__body no-pedding">
        <div class="list-section">                
            @forelse ($page as $item)
            
            <div class="list-section__item">
                <div class="section__content image-box">
                    <div class="section__desc">
                        <h5 class="section__title">{{ $item->judul }}</h5>
                        <div class="section__info">

                            <div class="section__info__item sm-text">
                                <span class="info__label">Posted By :</span>
                                <a href="" class="info__detail m-link">{{ $item->users->name }}</a>
                            </div>
                            <div class="section__info__item sm-text">
                                <span class="info__label">Language :</span>
                                <span class="info__detail">Indonesia</span>
                            </div>
                        </div>
                        <div class="section__status">
                            <span class="m-badge m-badge--danger m-badge--wide">Not Published yet</span>
                            <span class="m-badge m-badge--brand m-badge--wide">Draft</span>
                        </div>
                    </div>
                </div>
                <div class="section__action">
                    <div class="list__section__action">
                        <a href="#"
                            class="btn m-btn btn-primary btn-sm  m-btn--icon m-btn--square m-btn--air icon-only">
                            <span>
                                <i class="la la-list"></i>
                                <span>View List</span>
                            </span>
                        </a>
                        <a href="#" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--air icon-only">
                            <span>
                                <i class="la la-pencil"></i>
                                <span>View List</span>
                            </span>
                        </a>
                        <a href="#" class="btn m-btn btn-primary btn-sm m-btn--icon m-btn--pill m-btn--air icon-only">
                            <span>
                                <i class="la la-eye"></i>
                                <span>View Page</span>
                            </span>
                        </a>
                        <a href="#"
                            class="btn m-btn btn-outline-danger btn-sm  m-btn--icon m-btn--pill icon-only m_sweetalert_5">
                            <span>
                                <i class="la la-trash"></i>
                                <span>Delete</span>
                            </span>
                        </a>
                    </div>
                    <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push m-dropdown--up m--hide-desktop"
                        m-dropdown-toggle="click" aria-expanded="true">
                        <a href="#"
                            class="btn m-btn btn-outline-metal m-btn--icon btn-sm m-btn--icon-only m-btn--pill  m-dropdown__toggle">
                            <i class="la la-ellipsis-h"></i>
                        </a>
                        <div class="m-dropdown__wrapper" style="z-index: 101;">
                            <div class="m-dropdown__inner">
                                <div class="m-dropdown__body">
                                    <div class="m-dropdown__content">
                                        <!--Move Here-->
                                    </div>
                                </div>
                            </div>
                            <span class="m-dropdown__arrow m-dropdown__arrow--right"></span>
                        </div>
                    </div>
                </div>
            </div>
            @empty
            <p>Kosong</p>
            @endforelse            
        </div>
    </div>
</div>
@endsection