routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['verified' => true]);
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
Route::get('verifyemail/{token}','Auth\RegisterController@verify');
Route::group(['middleware' => ['auth','verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('artikel', 'ArtikelController');
    Route::post('/artikelFormData/{id}','ArtikelController@update');
    Route::post('deleteImageIsi','ArtikelController@deleteImageIsi');
    Route::get('getArtikel','ArtikelController@getTableArtikel');
    Route::put('gantiStatusArtikel/{id}','ArtikelController@gantiStatus');
    Route::resource('kategori', 'KategoriArtikelController');
    Route::get('getKategori','KategoriArtikelController@getTableKategori');
    Route::put('gantiStatusKategori/{id}','KategoriArtikelController@gantiStatus');
    Route::resource('menuGrouping', 'MenuGroupingController');
    Route::get('/getMenu','MenuGroupingController@getMenu');
    Route::get('usersIndex','ManagementUsersController@usersIndex');
    Route::get('createUsers','ManagementUsersController@createUsers');
    Route::post('oprationUsers','ManagementUsersController@storeUsers');
    Route::delete('oprationUsers/{id}','ManagementUsersController@destroyUsers');
    Route::get('oprationUsers/{id}/edit','ManagementUsersController@editUsers');
    Route::put('oprationUsers/{id}/','ManagementUsersController@updateUsers');    
    Route::get('getUsers','ManagementUsersController@getUsers');
    Route::get('roleAndPermission','ManagementUsersController@roleAndPermission');
    Route::post('addRole','ManagementUsersController@addRole');
    Route::post('addPermission','ManagementUsersController@addPermission');
    Route::resource('sectionArtikel', 'SectionArtikelController');
    Route::get('getSection','SectionArtikelController@getSection');
    Route::resource('kategoriPage', 'KategoriPageController');
    Route::get('getPagePerKategori/{id}','KategoriPageController@getPagePerKategori')->name('getPagePerKategori');
    Route::resource('page', 'PageController');
    // Route::get('getApi','ManagementUsersController@getApi');
});

resources/views/admin/kategori/buttonRole.blade.php
@role('Admin')
@if( $kategori->status_kategori === 0)
<button class="btn btn-primary m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="editKategoriModal" data-id="{{$kategori->id}}" data-label="{{$kategori->nama}}">>
  <i class="la la-archive"></i>
</button>
<button class="btn btn-danger m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="deleteKategoriModal" data-id="{{$kategori->id}}" data-label="{{$kategori->nama}}">
  <i class="la la-trash-o"></i>
</button>
<button class="btn btn-warning m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="gantiStatus" data-id="{{$kategori->id}}" data-label="{{$kategori->nama}}">
  <i class="la la-toggle-on"></i>
</button>
@else
<button class="btn btn-primary m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="editKategoriModal" data-id="{{$kategori->id}}" data-label="{{$kategori->nama}}">>
  <i class="la la-archive"></i>
</button>
<button class="btn btn-danger m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="deleteKategoriModal" data-id="{{$kategori->id}}" data-label="{{$kategori->nama}}">
  <i class="la la-trash-o"></i>
</button>
<button class="btn btn-warning m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="gantiStatus" data-id="{{$kategori->id}}" data-label="{{$kategori->nama}}">
  <i class="la la-toggle-off"></i>
</button>
@endif
@endrole

resources/views/admin/kategori/create.blade.php
@extends('layouts.app')
@section('title')
  Tambah Kategori
@endsection
@section('headerPage')
    Tambah Kategori
@endsection
@section('quickAction')
    <ul class="m-nav">
        <li>
            <li class="m-nav__section m-nav__section--first">
                <span class="m-nav__section-text">Quick Actions</span>
            </li>
            <li class="m-nav__item">
                <a href="{{ route('kategori.index') }}" class="m-nav__link">
                    <i class="m-nav__link-icon flaticon-share"></i>
                    <span class="m-nav__link-text">Lihat Seluruh Kategori</span>
                </a>
            </li>
        </li>
    </ul>
@endsection

@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
@if(session()->has('danger'))
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('danger') }}
</div>
@endif    
<form method="POST" action="{{route('kategori.store')}}">
    {{csrf_field()}}
    <div class="col-sm-12 m-form__group-sub">
        <label class="form-control-label">Nama</label>
        <input type="text" name="nama" class="form-control m-input" placeholder="Enter text">        
        <span class="m-form__help">Please enter your text</span>
    </div>
    <div class="col-sm-12 m-form__group-sub">
        <label class="form-control-label">Pilih Section</label>
        <select name="section_id" id="section_id" class="form-control m-imput">
            @foreach ($sections as $section)
                <option value="{{ $section->id }}">{{ $section->nama }}</option>
            @endforeach
        </select>        
    </div>
    <div class="col-xl-12 m--align-right">
        <button type="submit" class="btn btn-danger btn-sm m-btn--pill m-btn--air m-btn--wide m--margin-30">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm m-btn--wide m-btn--pill m--margin-left-5">Cancel</button>	
    </div>
</form>
@endsection

resources/views/admin/kategori/index.blade.php
@extends('layouts.app')
@section('title')
    Daftar Kategori
@endsection
@section('headerPage')
    Daftar Kategori
@endsection
@section('quickAction')
    <ul class="m-nav">
        <li>
            <li class="m-nav__section m-nav__section--first">
                <span class="m-nav__section-text">Quick Actions</span>
            </li>
            <li class="m-nav__item">
                <a href="{{ route('kategori.create') }}" class="m-nav__link">
                    <i class="m-nav__link-icon flaticon-share"></i>
                    <span class="m-nav__link-text">Tambah Kategori</span>
                </a>
            </li>
        </li>
    </ul>
@endsection
@section('isi')
<div class="m_datatable" id="kategori-table"></div>

<div class="modal fade" id="modalKategori" tabindex="-1" role="dialog" aria-labelledby="modalKategoriLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalKategoriLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="textInfo"></p>
                    <div id="formInfo">
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Nama Kategori</label>
                            <input type="name" class="form-control" name="nama" id="nama" id="exampleFormControlInput1" placeholder="Masukan Nama Kategori">
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="id" id="idParam">
                            <input type="hidden" name="_method" id="method">                            
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="buttonSubmit">Submit</button>
            </div>
        </div>
    </div>
</div>
@endsection