routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['verified' => true]);
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
Route::get('verifyemail/{token}','Auth\RegisterController@verify');
Route::group(['middleware' => ['auth','verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('artikel', 'ArtikelController');
    Route::post('/artikelFormData/{id}','ArtikelController@update');
    Route::post('deleteImageIsi','ArtikelController@deleteImageIsi');
    Route::get('getArtikel','ArtikelController@getTableArtikel');
    Route::put('gantiStatusArtikel/{id}','ArtikelController@gantiStatus');
    Route::resource('kategori', 'KategoriArtikelController');
    Route::get('getKategori','KategoriArtikelController@getTableKategori');
    Route::put('gantiStatusKategori/{id}','KategoriArtikelController@gantiStatus');
    Route::resource('menuGrouping', 'MenuGroupingController');
    Route::get('/getMenu','MenuGroupingController@getMenu');
    Route::get('usersIndex','ManagementUsersController@usersIndex');
    Route::get('createUsers','ManagementUsersController@createUsers');
    Route::post('oprationUsers','ManagementUsersController@storeUsers');
    Route::delete('oprationUsers/{id}','ManagementUsersController@destroyUsers');
    Route::get('oprationUsers/{id}/edit','ManagementUsersController@editUsers');
    Route::put('oprationUsers/{id}/','ManagementUsersController@updateUsers');    
    Route::get('getUsers','ManagementUsersController@getUsers');
    Route::get('roleAndPermission','ManagementUsersController@roleAndPermission');
    Route::post('addRole','ManagementUsersController@addRole');
    Route::post('addPermission','ManagementUsersController@addPermission');
    Route::resource('sectionArtikel', 'SectionArtikelController');
    Route::get('getSection','SectionArtikelController@getSection');
    Route::resource('kategoriPage', 'KategoriPageController');
    Route::get('getPagePerKategori/{id}','KategoriPageController@getPagePerKategori')->name('getPagePerKategori');
    Route::resource('page', 'PageController');
    // Route::get('getApi','ManagementUsersController@getApi');
});

app/Http/Controllers/MenuGroupingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\MenuGroupingModel;
use Auth;
use DataTables;

class MenuGroupingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.menuGrouping.index');
    }
    public function getMenu()
    {
        $getMenuGrouping = MenuGroupingModel::select(['id', 'nama']);

        return Datatables::of($getMenuGrouping)
            ->addColumn('action',function($menuGrouping){
                return view('admin.menuGrouping.buttonRole',['menuGrouping' => $menuGrouping])->render();
            })
        ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.menuGrouping.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $menu = new MenuGroupingModel();
            $menu->users_id = Auth::user()->id;
            $menu->nama = $request->input('nama');
            $menu->save();
            return back()->with('success','Data Berhasil di Tambahkan');
        } catch (\Exception $e) {
            return back()->with('danger', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $menu = MenuGroupingModel::findOrFail($id);
        return response()->json($menu,200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $menu = MenuGroupingModel::findOrFail($id);
            $menu->users_id = Auth::user()->id;
            $menu->nama = $request->input('nama');
            $menu->save();        
        } catch (\Exception $e) {
            return response()->json([
                'message' => $e->getMessage(),
                'error' => true
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $menu = MenuGroupingModel::findOrFail($id);
            $menu->delete();
        } catch (\Exception $e) {
            return response()->json([
                'message' => $e->getMessage(),
                'error' => true
            ]);
        }
    }
}

resources/views/admin/menuGrouping/buttonRole.blade.php
@role('Admin')
<button class="btn btn-primary m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="editMenuGroupingModal" data-id="{{$menuGrouping->id}}" data-label="{{$menuGrouping->nama}}">
  <i class="la la-archive"></i>
</button>
<button class="btn btn-danger m-btn m-btn--icon m-btn--icon-only m-btn--pill" id="deleteMenuGroupingModal" data-id="{{$menuGrouping->id}}" data-label="{{$menuGrouping->nama}}">
  <i class="la la-trash-o"></i>
</button>
@endrole

resources/views/admin/menuGrouping/create.blade.php
@extends('layouts.app')
@section('title')
    Tambah Menu
@endsection
@section('headerPage')
    Tambah Menu
@endsection
@section('quickAction')
    <ul class="m-nav">
        <li>
            <li class="m-nav__section m-nav__section--first">
                <span class="m-nav__section-text">Quick Actions</span>
            </li>
            <li class="m-nav__item">
                <a href="{{ route('menuGrouping.index') }}" class="m-nav__link">
                    <i class="m-nav__link-icon flaticon-share"></i>
                    <span class="m-nav__link-text">Lihat Menu</span>
                </a>
            </li>
        </li>
    </ul>
@endsection
@section('isi')
@if ($errors->any())    
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session()->has('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
        {{ session()->get('success') }}
</div>
@endif
<form method="POST" action="{{route('menuGrouping.store')}}">
    @csrf
        <div class="form-group">
            <label>Nama</label>
            <input type="name" class="form-control" name="nama" placeholder="Masukan Nama Menu">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
</form>        

@endsection

resources/views/admin/menuGrouping/index.blade.php
@extends('layouts.app')
@section('title')
    Daftar Menu
@endsection
@section('headerPage')
    Daftar Menu
@endsection
@section('quickAction')
    <ul class="m-nav">
        <li>
            <li class="m-nav__section m-nav__section--first">
                <span class="m-nav__section-text">Quick Actions</span>
            </li>
            <li class="m-nav__item">
                <a href="{{ route('menuGrouping.create') }}" class="m-nav__link">
                    <i class="m-nav__link-icon flaticon-share"></i>
                    <span class="m-nav__link-text">Tambah Menu</span>
                </a>
            </li>
        </li>
    </ul>
@endsection
@section('isi')
<div class="m_datatable" id="menuGrouping-table"></div>
<div class="modal fade" id="modalMenuGrouping" tabindex="-1" role="dialog" aria-labelledby="modalMenuGroupingLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalMenuGroupingLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="triggerReset">
                {{csrf_field()}}
                <div class="modal-body">
                    <p id="textInfo"></p>
                    <div id="formInfo" class="m-scrollable" data-scrollbar-shown="true" data-scrollable="true" data-height="200" style="overflow: auto; height: 200px;">
                        <div class="form-group">
                            <label for="exampleFormControlInput1">Menu</label>
                            <input type="name" class="form-control" name="nama" id="nama" id="exampleFormControlInput1" placeholder="Masukan Nama Menu">
                            <input type="hidden" name="id" id="idParam">
                            <input type="hidden" name="_method" id="method">                        
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="buttonSubmit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection